# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-06-13 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='user',
            name='portrait',
            field=models.CharField(default='/static/img/man.jpg', max_length=256, verbose_name='头像'),
        ),
    ]
